### ISSUE TITLE
Used to be so easy with Magisk....total fail with Vanced Manager

### ISSUE THREAD

**Issue by stylemessiah** [YTVanced/VancedInstaller#20]
Grievance #1 

Upon entering Vanced Manager the option to download Youtube Vanced is disabled, with the button saying No MicroG (but inactive). For starters why should i want MicroG just to use Youtube Vanced? Never have before. 

Curiously, going into settings and enabling Root mode, and returning to main scree, the button is enabled...which leads us nicely to .....

Grievance #2 

Pressing the download button, take sme through to English (tick), Black (tick) starts downloading

config.xxxx for arm7 .apk completes
black.apk gets to about 3/4 and dies 

Replicated about 20 times, with storage resetting, reboots etc...

Cannot get past this

Why does what was a magisk module flash now have to go through all this malarkey?

Grievance #3 

Trying to download from vanced.app on phone yields .bin files...wtf? I assume a rename to .apks will work, but ....

Trying download on PC yields .apks files...this looks like how it should be...

If this is progress, i wish to remain a luddite :)

**Comment by X1nto** [comment]
1. Maybe you should actually read what button says and just install microg. Vanced won't work without microg.

2. Download issue is being addressed and it's issue with library, we're trying out new library that should solve this issue.

3. It's issue with Firefox, just rename .bin files to .apks

Bonus:
Magisk module is deprecated because vanced needs signature verification disabled and no magisk module can't do this (yet).

**Comment by stylemessiah** [comment]
So im staying with the old magisk module until a new one come sout then, as im not doing all the malarkey with disabling this and that with xposed (which breaks other things). Just hell no

Cheers for the explanation.
